name: Reset packages
on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/scripts/root.Dockerfile
      - last_bioc_set
jobs:
  packages-reset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true

      - id: variables
        run: |
          echo platform=$(cat PLATFORM.bioc) >> $GITHUB_OUTPUT
          echo rootcontainer=$(cat ROOT_CONTAINER.bioc) >> $GITHUB_OUTPUT
          mkdir -p /tmp/image

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
        if: contains(steps.variables.outputs.platform, 'arm64')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ steps.variables.outputs.platform }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container with root user
        id: dockerbuild
        uses: docker/build-push-action@v3
        with:
          file: .github/scripts/root.Dockerfile
          push: false
          load: false
          outputs: type=tar,dest=/tmp/image/bioc_build.tar
          context: .
          cache-to: type=gha,mode=max,scope=${{ steps.meta.outputs.image }}
          tags: ${{ steps.variables.outputs.rootcontainer }}
          platforms: ${{ steps.variables.outputs.platform }}

      - name: Copy old run
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 50
          shell: bash
          command: |
            set -x
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git pull origin main || git reset --hard origin/main
            STARTTIME="$(cat runstarttime)" || true
            LOGDIR="logs/$(cat runstarttime)" || true
            mv runstarttime "$LOGDIR"/ || true
            mv uniquedeps.json "$LOGDIR"/ || true
            mv packages.json "$LOGDIR"/ || true
            mv biocdeps.json "$LOGDIR"/ || true
            mv tobuild.txt "$LOGDIR"/ || true
            mv lists "$LOGDIR"/lists || true

            repodir=$(pwd)
            mkdir -p bioc_build

            (cd /tmp/image && tar -xvf bioc_build.tar && cp -r tmp/bioc_build $repodir/)

            mv bioc_build/uniquedeps.json ./
            mv bioc_build/biocdeps.json ./
            cp biocdeps.json packages.json
            cp bioc_build/containername containername
            cp bioc_build/arch arch

            bash .github/scripts/reset_packages.sh
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git add .
            git commit -m "Reset packages $STARTTIME"
            git push
